version: '3.8'

services:
  frontend:
    build: .
    networks:
    - app-network

  frontend_test:
    build: .

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network
    
  nginx_test:
    image: nginx:latest
    container_name: nginx_test
    volumes:
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_test

networks:
  app-network:
    driver: bridge
